.TH "Analytic_Circumference" 3 "Fri Mar 27 2020" "Version 1.0" "Analytic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analytic_Circumference \- Circumference structure ( $x^2 + y^2 + ax + by + c = 0$)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Circumference structure ( $x^2 + y^2 + ax + by + c = 0$) 


.SH "Field Documentation"
.PP 
.SS "float a"
First Coefficient of the equation 
.SS "float b"
Second Coefficient of the equation 
.SS "float c"
Third Coefficient of the equation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Analytic from the source code\&.
