.TH "Analytic_Line" 3 "Fri Mar 27 2020" "Version 1.0" "Analytic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analytic_Line \- Straight Line Structure ( $y = mx + q$)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBm\fP"
.br
.ti -1c
.RI "float \fBq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Straight Line Structure ( $y = mx + q$) 


.SH "Field Documentation"
.PP 
.SS "float m"
Straight line coefficient 
.SS "float q"
Known term of the line 

.SH "Author"
.PP 
Generated automatically by Doxygen for Analytic from the source code\&.
