.TH "Analytic_Position" 3 "Fri Mar 27 2020" "Version 1.0" "Analytic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analytic_Position \- Position structure (Contains the coordinates of a point)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Position structure (Contains the coordinates of a point) 


.SH "Field Documentation"
.PP 
.SS "float x"
X coordinate 
.SS "float y"
Y coordinate 

.SH "Author"
.PP 
Generated automatically by Doxygen for Analytic from the source code\&.
