.TH "draw.c" 3 "Fri Mar 27 2020" "Version 1.0" "Analytic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
draw.c \- Analytic, a simple program for the graphic representation of the most common geometric places: Straight lines, Circumferences, Hyperbolas and Parables\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <analytic/analytic\&.h>\fP
.br
\fC#include <analytic/global\&.h>\fP
.br
\fC#include <analytic/scale\&.h>\fP
.br
\fC#include <analytic/functions\&.h>\fP
.br
\fC#include <analytic/geometry\&.h>\fP
.br
\fC#include <analytic/plane\&.h>\fP
.br
\fC#include <log/log\&.h>\fP
.br
\fC#include <ui/input\&.h>\fP
.br
\fC#include <ui/output\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char const *argv[])"
.br
.RI "Main method of the program\&. "
.in -1c
.SH "Detailed Description"
.PP 
Analytic, a simple program for the graphic representation of the most common geometric places: Straight lines, Circumferences, Hyperbolas and Parables\&. 


.PP
\fBAuthor\fP
.RS 4
Marco Mihai Condrache (marcomihaicondrache@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
25-03-2020
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2020
.RE
.PP
https://github.com/MarcoMihaiCondrache 
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char const * argv[])"

.PP
Main method of the program\&. Main method of the program, controls the windo 
.br
and manages external inputs and events such as the 
.br
control on the mouse wheel 
.br
 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP 
.br
\fIargv\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Analytic from the source code\&.
