.TH "ui/global.h" 3 "Fri Mar 27 2020" "Version 1.0" "Analytic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui/global.h \- UI global file contains global definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRAILING\fP   '~ >>> '"
.br
.RI "Defines the indicator to be printed before a scanf\&. "
.ti -1c
.RI "#define \fBCLEAR\fP   'clear'"
.br
.RI "Defines the command to use to clear the console (The preprocessor result depends on the operating system) "
.in -1c
.SH "Detailed Description"
.PP 
UI global file contains global definitions\&. 


.PP
\fBAuthor\fP
.RS 4
Marco Mihai Condrache (marcomihaicondrache@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
25-03-2020
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2020
.RE
.PP
https://github.com/MarcoMihaiCondrache 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEAR   'clear'"

.PP
Defines the command to use to clear the console (The preprocessor result depends on the operating system) 
.SS "#define TRAILING   '~ >>> '"

.PP
Defines the indicator to be printed before a scanf\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Analytic from the source code\&.
